.PHONY: clean All

All:
	@echo "----------Building project:[ cc_search - Debug ]----------"
	@$(MAKE) -f  "cc_search.mk"
clean:
	@echo "----------Cleaning project:[ cc_search - Debug ]----------"
	@$(MAKE) -f  "cc_search.mk" clean
