.PHONY: clean All

All:
	@echo "----------Building project:[ decoder - Debug ]----------"
	@$(MAKE) -f  "decoder.mk"
clean:
	@echo "----------Cleaning project:[ decoder - Debug ]----------"
	@$(MAKE) -f  "decoder.mk" clean
