.PHONY: clean All

All:
	@echo "----------Building project:[ detector - Debug ]----------"
	@$(MAKE) -f  "detector.mk"
clean:
	@echo "----------Cleaning project:[ detector - Debug ]----------"
	@$(MAKE) -f  "detector.mk" clean
